#' AdjCreateBarChart
#'
#' Create a bar chart of mean adjusted off-target editing per sample
#'
#' Creates a bar chart using the mean background-adjusted off-target editing
#' values generated by \code{\link{AdjustedMeanCalc}}.
#'
#' @param AdjustedMean Data frame containing mean background-adjusted
#'   off-target editing values generated by \code{\link{AdjustedMeanCalc}}.
#'   Must contain \code{SampleName} and \code{Off target \%}.
#' @param SampleList Data frame containing sample metadata, including
#'   \code{SampleName} and \code{Order}, used to determine plotting order.
#' @param colour Colour used to fill the bars. Default is \code{"skyblue"}.
#' @param out_dir_base Base analysis directory. Defaults to the current working
#'   directory (\code{"."}). The plot is written to the
#'   \code{Plots/AdjustedPlots} subdirectory within this directory.
#'
#' @return Invisibly returns the ggplot object. PNG and PDF versions of the
#'   bar chart are saved to the \code{Plots/AdjustedPlots} subdirectory within
#'   \code{out_dir_base}.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' AdjustedMean <- AdjustedMeanCalc(
#'   Adj = Adj,
#'   OntargetPosition = 1561
#' )
#'
#' AdjCreateBarChart(
#'   AdjustedMean = AdjustedMean,
#'   SampleList = SampleList,
#'   colour = "skyblue"
#' )
#' }

AdjCreateBarChart <- function(
    AdjustedMean,
    SampleList,
    colour = "skyblue",
    out_dir_base = "."
) {

  # Check required columns
  required_mean_columns <- c(
    "SampleName",
    "Off target %"
  )

  missing_mean_columns <- setdiff(
    required_mean_columns,
    names(AdjustedMean)
  )

  if (length(missing_mean_columns) > 0) {
    stop(
      "Error: Missing required column(s) in AdjustedMean: ",
      paste(missing_mean_columns, collapse = ", ")
    )
  }

  required_sample_columns <- c(
    "SampleName",
    "Order"
  )

  missing_sample_columns <- setdiff(
    required_sample_columns,
    names(SampleList)
  )

  if (length(missing_sample_columns) > 0) {
    stop(
      "Error: Missing required column(s) in SampleList: ",
      paste(missing_sample_columns, collapse = ", ")
    )
  }

  # Use the adjusted mean calculated by AdjustedMeanCalc()
  data <- AdjustedMean %>%
    dplyr::filter(
      !is.na(.data$`Off target %`)
    )

  # Add plotting order
  data$Order <- as.integer(
    SampleList$Order[
      match(
        data$SampleName,
        SampleList$SampleName
      )
    ]
  )

  if (any(is.na(data$Order))) {
    warning(
      "One or more samples in AdjustedMean could not be matched ",
      "to SampleList for plotting order."
    )
  }

  # Set sample order
  ordered_samples <- SampleList$SampleName[
    order(SampleList$Order)
  ]

  data$SampleName <- factor(
    data$SampleName,
    levels = rev(ordered_samples)
  )

  # Output directory
  the_dir <- file.path(
    out_dir_base,
    "Plots",
    "AdjustedPlots"
  )

  check_create_dir(the_dir)

  # Create bar chart
  p <- ggplot2::ggplot(
    data,
    ggplot2::aes(
      x = .data$SampleName,
      y = .data$`Off target %`
    )
  ) +
    ggplot2::geom_bar(
      stat = "identity",
      fill = colour,
      alpha = 0.7
    ) +
    ggplot2::geom_text(
      ggplot2::aes(
        label = sprintf(
          "%.2f",
          .data$`Off target %`
        )
      ),
      hjust = 1.6,
      colour = "black",
      size = 4.5
    ) +
    ggplot2::labs(
      x = NULL,
      y = "Adjusted off-target editing (%)"
    ) +
    ggplot2::scale_y_continuous(
      expand = c(0, 0)
    ) +
    ggplot2::scale_x_discrete(
      expand = c(0, 0)
    ) +
    ggplot2::theme_classic(
      base_size = 13
    ) +
    ggplot2::theme(
      axis.text.y = ggplot2::element_text(size = 13),
      axis.text.x = ggplot2::element_text(size = 12),
      axis.title = ggplot2::element_text(size = 14)
    ) +
    ggplot2::coord_flip()

  # Save plot
  ggplot2::ggsave(
    file.path(
      the_dir,
      "Adjusted_Barchart_offTarget.png"
    ),
    plot = p,
    width = 8,
    height = 6,
    dpi = 300
  )

  ggplot2::ggsave(
    file.path(
      the_dir,
      "Adjusted_Barchart_offTarget.pdf"
    ),
    plot = p,
    width = 8,
    height = 6
  )

  invisible(p)
}
