#' AdjustedMeanCalc
#'
#' Calculate mean background-adjusted off-target editing
#'
#' Calculates the mean adjusted off-target editing percentage for each sample
#' directly from the position-level output generated by
#' \code{\link{AdjOffTarget}}. The on-target position is excluded before
#' calculating the mean. Positions with \code{NA} adjusted percentages are
#' excluded from the calculation and are not treated as zero.
#'
#' @param Adj A data frame containing position-level background-adjusted
#'   editing values generated by \code{\link{AdjOffTarget}}.
#' @param OntargetPosition Numeric position of the intended on-target edit.
#' @param out_dir_base Base output directory. Defaults to the current working
#'   directory (`"."`). The `Overview` subdirectory is created within this
#'   directory.
#'
#' @return A data frame containing the mean background-adjusted off-target
#'   percentage for each sample. The same data are written to
#'   `Overview/All_OffTarget_Adjusted_Mean.csv`.
#'
#' @keywords off-target adjusted mean summary
#' @export
#'
#' @examples
#' \dontrun{
#' AdjustedMean <- AdjustedMeanCalc(
#'   Adj = Adj,
#'   OntargetPosition = 1561
#' )
#' }

AdjustedMeanCalc <- function(
    Adj,
    OntargetPosition,
    out_dir_base = "."
) {

  required_columns <- c(
    "FileName",
    "SampleName",
    "Condition",
    "position",
    "AdjPercentage"
  )

  missing_columns <- setdiff(
    required_columns,
    names(Adj)
  )

  if (length(missing_columns) > 0) {
    stop(
      "Error: Missing required column(s) in Adj: ",
      paste(missing_columns, collapse = ", ")
    )
  }

  df <- Adj %>%
    dplyr::filter(
      .data$position != OntargetPosition
    ) %>%
    dplyr::group_by(
      .data$FileName,
      .data$SampleName,
      .data$Condition
    ) %>%
    dplyr::summarise(
      `Off target %` = mean(
        .data$AdjPercentage,
        na.rm = TRUE
      ),
      .groups = "drop"
    )

  the_dir <- file.path(
    out_dir_base,
    "Overview"
  )

  check_create_dir(the_dir)

  readr::write_csv(
    df,
    file.path(
      the_dir,
      "All_OffTarget_Adjusted_Mean.csv"
    )
  )

  return(df)
}
