#' CalcAllMutations
#'
#' Identify the most abundant mismatch at each position
#'
#' Uses the AllPositions output generated by MitoBEAP to report the most
#' abundant non-reference base at each position. For a complete
#' chemistry-independent spectrum containing all non-reference substitutions,
#' use \code{\link{CalculateMismatchSpectrum}}.
#'
#' @param AllReportFiles Optional character vector of input CSV file paths.
#'   If not supplied, files ending in `_counts.csv` are read from the
#'   `AllPositions` subdirectory within `out_dir_base`.
#' @param out_dir_base Base analysis directory. Defaults to the current working
#'   directory (`"."`). Input files are read from the `AllPositions`
#'   subdirectory when `AllReportFiles` is not supplied, and output is written
#'   to the `AllMutations` subdirectory.
#' @return Invisibly returns \code{NULL}. For each input file, the function
#'   writes a CSV file containing the most abundant non-reference base at each
#'   position, its read depth, total coverage, and mismatch percentage to the
#'   `AllMutations` subdirectory.
#' @export
CalcAllMutations <- function(
    AllReportFiles = NULL,
    out_dir_base = "."
) {

  if (is.null(AllReportFiles)) {

    allpositions_dir <- file.path(
      out_dir_base,
      "AllPositions"
    )

    AllReportFiles <- list.files(
      allpositions_dir,
      pattern = "_counts\\.csv$",
      full.names = TRUE
    )

    if (length(AllReportFiles) == 0) {
      stop(
        "Error: No AllPositions count files found in '",
        allpositions_dir,
        "'."
      )
    }
  }

  process_file <- function(input) {

    df <- readr::read_csv(
      input,
      show_col_types = FALSE
    )

    required_columns <- c(
      "position",
      "RefBase",
      "MutBase",
      "MutReads",
      "depth",
      "percentage"
    )

    missing_columns <- setdiff(
      required_columns,
      names(df)
    )

    if (length(missing_columns) > 0) {
      stop(
        "Error: Missing required column(s) in '",
        basename(input),
        "': ",
        paste(missing_columns, collapse = ", ")
      )
    }

    new_df <- data.frame(
      position = df$position,
      RefSeq = df$RefBase,
      HighestMM = df$MutBase,
      MMDepth = df$MutReads,
      Coverage = df$depth,
      MM_percentage = df$percentage
    )

    # Positions without a retained mismatch have zero mismatch reads
    # and zero mismatch percentage.
    no_mismatch <- is.na(new_df$HighestMM)

    new_df$MMDepth[no_mismatch] <- 0
    new_df$MM_percentage[no_mismatch] <- 0

    the_dir <- file.path(
      out_dir_base,
      "AllMutations"
    )

    check_create_dir(the_dir)

    readr::write_csv(
      new_df,
      file.path(
        the_dir,
        paste0(
          tools::file_path_sans_ext(
            basename(input)
          ),
          "_Highest_Mutation.csv"
        )
      )
    )
  }

  lapply(
    AllReportFiles,
    process_file
  )

  invisible(NULL)
}
