#' CreateOverview
#'
#' Combines off-target mean editing values, on-target editing, coverage, and
#' sample metadata into a single overview table.
#'
#' The off-target mean input may contain either the original unadjusted
#' off-target means generated by `MeanCalc()` or the background-adjusted
#' off-target means generated by `AdjustedMeanCalc()`.
#'
#' @param All_mean Data frame containing mean off-target editing values.
#'   This may be the unadjusted output from `MeanCalc()` or the adjusted
#'   output from `AdjustedMeanCalc()`. Defaults to the global `All_mean`
#'   object if not supplied.
#' @param OnTarget Data frame containing on-target editing values.
#'   Defaults to the global `OnTarget` object if not supplied.
#' @param Coverage Data frame containing coverage values.
#'   Defaults to the global `Coverage` object if not supplied.
#' @param SampleList Data frame containing sample metadata.
#'   Defaults to the global `SampleList` object if not supplied.
#' @param cleanup Logical. If `TRUE`, intermediate output directories
#'   (`minimum`, `Coverage`, `mean`, `OnTarget`, and `percentages`) are
#'   deleted after the overview file is created. Default is `FALSE`.
#' @param out_dir_base Base analysis directory. Defaults to the current working
#'   directory (`"."`). The overview file is written to the `Overview`
#'   subdirectory.
#' @param output_file Character. Filename for the overview CSV written to the
#'   `Overview` directory. Default is `"All_Ontarget_mean_Coverage.csv"`.
#' @param coverage_ratio_warning Numeric coverage ratio above which a warning
#'   is issued when the highest-coverage sample exceeds the lowest-coverage
#'   sample by this factor. Default is 10. Set to `NULL` to disable the check.
#'
#' @return Invisibly returns the combined overview data frame. The same data
#'   are written to the specified `output_file` in the `Overview` directory.
#' @export
#'
#' @examples
#' \dontrun{
#' CreateOverview(
#'   All_mean = Mean,
#'   OnTarget = OnTarget,
#'   Coverage = Coverage,
#'   SampleList = SampleList
#' )
#' }

CreateOverview <- function(
    All_mean = NULL,
    OnTarget = NULL,
    Coverage = NULL,
    SampleList = NULL,
    cleanup = FALSE,
    out_dir_base = ".",
    output_file = "All_Ontarget_mean_Coverage.csv",
    coverage_ratio_warning = 10
) {

  # Use supplied objects; fall back to global objects for backward compatibility
  if (is.null(All_mean)) {
    if (!exists("All_mean", envir = .GlobalEnv, inherits = FALSE)) {
      stop("Error: 'All_mean' must be supplied or exist in the global environment.")
    }
    All_mean <- get("All_mean", envir = .GlobalEnv, inherits = FALSE)
  }

  if (is.null(OnTarget)) {
    if (!exists("OnTarget", envir = .GlobalEnv, inherits = FALSE)) {
      stop("Error: 'OnTarget' must be supplied or exist in the global environment.")
    }
    OnTarget <- get("OnTarget", envir = .GlobalEnv, inherits = FALSE)
  }

  if (is.null(Coverage)) {
    if (!exists("Coverage", envir = .GlobalEnv, inherits = FALSE)) {
      stop("Error: 'Coverage' must be supplied or exist in the global environment.")
    }
    Coverage <- get("Coverage", envir = .GlobalEnv, inherits = FALSE)
  }

  if (is.null(SampleList)) {
    if (!exists("SampleList", envir = .GlobalEnv, inherits = FALSE)) {
      stop("Error: 'SampleList' must be supplied or exist in the global environment.")
    }
    SampleList <- get("SampleList", envir = .GlobalEnv, inherits = FALSE)
  }

  # Check required columns
  if (!all(c("FileName", "Off target %") %in% names(All_mean))) {
    stop("Error: 'All_mean' must contain 'FileName' and 'Off target %'.")
  }

  if (!all(c("FileName", "On target %") %in% names(OnTarget))) {
    stop("Error: 'OnTarget' must contain 'FileName' and 'On target %'.")
  }

  if (!all(c("FileName", "Coverage") %in% names(Coverage))) {
    stop("Error: 'Coverage' must contain 'FileName' and 'Coverage'.")
  }

  if (!all(c("FileName", "SampleName", "Order") %in% names(SampleList))) {
    stop("Error: 'SampleList' must contain 'FileName', 'SampleName', and 'Order'.")
  }

  # Clean file names
  All_mean$FileName <- sub("_mean$", "", All_mean$FileName)
  OnTarget$FileName <- sub("_ontarget$", "", OnTarget$FileName)
  Coverage$FileName <- sub("_coverage$", "", Coverage$FileName)

  # Ensure numerical values are numeric
  All_mean$`Off target %` <- suppressWarnings(
    as.numeric(All_mean$`Off target %`)
  )

  OnTarget$`On target %` <- suppressWarnings(
    as.numeric(OnTarget$`On target %`)
  )

  Coverage$Coverage <- suppressWarnings(
    as.numeric(Coverage$Coverage)
  )

  # Match on-target editing
  idx3 <- match(All_mean$FileName, OnTarget$FileName)
  All_mean$`On target %` <- OnTarget$`On target %`[idx3]

  # Match coverage
  idx4 <- match(All_mean$FileName, Coverage$FileName)
  All_mean$Coverage <- Coverage$Coverage[idx4]

  # Warn when sequencing coverage differs substantially across samples
  if (!is.null(coverage_ratio_warning)) {

    if (!is.numeric(coverage_ratio_warning) ||
        length(coverage_ratio_warning) != 1 ||
        is.na(coverage_ratio_warning) ||
        coverage_ratio_warning <= 1) {
      stop(
        "'coverage_ratio_warning' must be a single numeric value greater than 1, or NULL."
      )
    }

    coverage_values <- All_mean$Coverage
    coverage_values <- coverage_values[
      is.finite(coverage_values) & coverage_values > 0
    ]

    if (length(coverage_values) >= 2) {

      coverage_ratio <- max(coverage_values) / min(coverage_values)

      if (coverage_ratio > coverage_ratio_warning) {
        warning(
          sprintf(
            paste0(
              "Sequencing coverage differs by %.1f-fold across samples ",
              "(minimum %.1fx; maximum %.1fx). ",
              "This exceeds the coverage warning threshold of %.1f-fold. ",
              "Differences in sequencing depth may affect comparisons of ",
              "low-frequency editing events."
            ),
            coverage_ratio,
            min(coverage_values),
            max(coverage_values),
            coverage_ratio_warning
          ),
          call. = FALSE
        )
      }
    }
  }

  # Add sample metadata
  idx5 <- match(All_mean$FileName, SampleList$FileName)
  All_mean$RealName <- SampleList$SampleName[idx5]
  All_mean$Order <- SampleList$Order[idx5]

  # Sort according to sample order
  All_mean <- dplyr::arrange(All_mean, .data$Order)

  # Create output directory
  the_dir <- file.path(out_dir_base, "Overview")
  check_create_dir(the_dir)

  # Write overview
  readr::write_csv(
    All_mean,
    file.path(the_dir, output_file)
  )

  # Optionally clean up intermediate folders
  if (isTRUE(cleanup)) {
    unlink(file.path(out_dir_base, "minimum"), recursive = TRUE)
    unlink(file.path(out_dir_base, "Coverage"), recursive = TRUE)
    unlink(file.path(out_dir_base, "mean"), recursive = TRUE)
    unlink(file.path(out_dir_base, "OnTarget"), recursive = TRUE)
    unlink(file.path(out_dir_base, "percentages"), recursive = TRUE)
  }

  return(invisible(All_mean))
}
