#' Combine and adjust highest-mismatch results
#'
#' @description
#' Combines the highest non-reference mutation identified at each mitochondrial
#' position across samples and applies control-based background masking.
#' Positions exceeding the specified mismatch threshold in the required number
#' of control samples are assigned \code{NA} in the \code{AdjPercentage}
#' column. The function uses the output generated by
#' \code{\link{CalcAllMutations}}.
#' @param min_threshold Numeric; minimum heteroplasmy level to take into account, Default = 0
#' @param max_threshold Numeric; maximum heteroplasmy level in the controls to take into account, Default = 60
#' @param controls Numeric; number of controls that need to have heteroplasmy level above max_threshold. Default = 2
#' @param SampleList Data frame containing sample metadata.
#'   Defaults to the global `SampleList` object if not supplied.
#' @param out_dir_base Base analysis directory. Defaults to the current working
#'   directory (`"."`). Input files are read from the `AllMutations`
#'   subdirectory within this directory.
#' @return A data frame containing the mutation data with the adjusted
#'   percentage in `AdjPercentage`.
#' @export
DdCBE_df_All <- function(
    min_threshold = 0,
    max_threshold = 60,
    controls = 2,
    SampleList = NULL,
    out_dir_base = "."
) {

  if (is.null(SampleList)) {
    if (!exists("SampleList", envir = .GlobalEnv, inherits = FALSE)) {
      stop("Error: 'SampleList' must be supplied or exist in the global environment.")
    }
    SampleList <- get("SampleList", envir = .GlobalEnv, inherits = FALSE)
  }

  all_mutations_dir <- file.path(out_dir_base, "AllMutations")

  AllMutFiles <- list.files(
    all_mutations_dir,
    pattern = "_Highest_Mutation\\.csv$",
    full.names = TRUE
  )

  if (length(AllMutFiles) == 0) {
    stop("Error: No mutation files found in '", all_mutations_dir, "'.")
  }

  df7 <- AllMutFiles %>%
    purrr::set_names(nm = (basename(.) %>% tools::file_path_sans_ext())) %>% # Name without extension
    purrr::map_df(read_csv,
                  col_names = TRUE,
                  skip = 0,
                  .id = "FileName")
  df7$FileName <- gsub(pattern = "_R30_allMutations_Highest_Mutation", "", x=df7$FileName)

  idx5 <- match(df7$FileName, SampleList$FileName)
  df7$SampleName <- SampleList$SampleName [idx5]
  df7$Condition <- SampleList$Condition [idx5]

  # Apply max thresholds on control samples to know which positions to ignore
  df8 <- df7[df7$Condition == "control" & (df7$MM_percentage >= max_threshold), ]

  subset <- df8 %>%
    dplyr::group_by(position) %>%
    dplyr::filter(dplyr::n_distinct(FileName) >= controls) %>%
    dplyr::ungroup()

  df10 <- unique(subset$position)

  df11 <- df7 %>%
    mutate(AdjPercentage = case_when(
      position %in% df10 ~ NA,
      TRUE ~ df7$MM_percentage
    )
    )

  return(df11)

}
