#' OnTargetCalcCBE
#'
#' Analyzes count files to calculate base editing efficiency (C→T and G→A conversions), including on- and off-target effects.
#' Saves outputs like mutation percentages, mean off-target values, on-target editing rates, coverage, and annotated full data.
#'
#' @param MinXFiles A character vector of file paths to pre-filtered count data (CSV format).
#' @param OntargetPosition Numeric. Genomic position of the intended on-target
#'   editing site.
#' @param out_dir_base Base output directory. Defaults to the current working
#'   directory (`"."`). The `percentages`, `mean`, `OnTarget`, `Coverage`,
#'   and `AllPositions` subdirectories are created within this directory.
#' @keywords CBE, base editing, efficiency, on-target, off-target
#' @export
#' @examples
#' \dontrun{
#' file_paths <- c("file1.csv", "file2.csv", "file3.csv")
#' OnTargetCalcCBE(file_paths, OntargetPosition = 1561) # replace 1561 with your on-target position
#' }

OnTargetCalcCBE <- function(
    MinXFiles,
    OntargetPosition,
    out_dir_base = "."
) {
  # Check file existence
  if (any(!file.exists(MinXFiles))) {
    stop("One or more input files not found.")
  }

  process_file <- function(input) {
    message("Processing: ", input)
    data <- read.delim(input, row.names = NULL, header = T, sep = ",")

    # Install the 'splitstackshape' package if needed: install.packages("splitstackshape")
    if (!requireNamespace("splitstackshape", quietly = TRUE)) {
      stop("Please install the 'splitstackshape' package to use the 'concat.split' function.")
    }

    # Identify the VarScan allele columns generated by LoadRawCount()
    allele_cols <- intersect(
      c("A6", "A7", "A8", "A9"),
      names(data)
    )

    if (length(allele_cols) == 0) {
      stop(
        "No VarScan allele columns (A6-A9) were found in the input file: ",
        basename(input)
      )
    }

    # Split the VarScan allele fields into their named components.
    # Component 1 contains the allele/base and component 2 the read count.
    data <- splitstackshape::concat.split(
      data = data,
      split.col = allele_cols,
      sep = ":",
      drop = TRUE
    )

    allele_pair_cols <- unlist(
      lapply(
        allele_cols,
        function(x) paste0(x, c("_1", "_2"))
      ),
      use.names = FALSE
    )

    required_cols <- c(
      "chrom",
      "position",
      "ref_base",
      "depth",
      allele_pair_cols
    )

    missing_cols <- setdiff(required_cols, names(data))

    if (length(missing_cols) > 0) {
      stop(
        "Required columns are missing after parsing VarScan data: ",
        paste(missing_cols, collapse = ", ")
      )
    }

    # Select columns by name rather than by numeric position
    data <- data[, required_cols, drop = FALSE]

    # Add columns if they don't exist
    rename_map <- c(
      A6_1 = "base.1",
      A6_2 = "reads.1",
      A7_1 = "base.2",
      A7_2 = "reads.2",
      A8_1 = "base.3",
      A8_2 = "reads.3",
      A9_1 = "base.4",
      A9_2 = "reads.4"
    )

    for (old_name in names(rename_map)) {
      if (old_name %in% names(data)) {
        names(data)[names(data) == old_name] <- rename_map[[old_name]]
      }
    }

    # Ensure all four nucleotide allele slots exist.
    # VarScan output can contain fewer allele fields when some bases are absent.
    for (i in 1:4) {
      base_col <- paste0("base.", i)
      reads_col <- paste0("reads.", i)

      if (!base_col %in% names(data)) {
        data[[base_col]] <- NA_character_
      }

      if (!reads_col %in% names(data)) {
        data[[reads_col]] <- NA_real_
      }
    }

    # Select all C
    data2C <- data[data$ref_base %in% c("C"),]
    # Select all G
    data2G <- data[data$ref_base %in% c("G"),]
    # Combine data2C and data2G for later
    dataCG <- rbind(data2C, data2G)

    # For data2C select the reads that have a T
    data3C.1 <- subset(data2C, base.1 %in% c("T"), select=c("chrom", "position",  "ref_base", "depth", "base.1", "reads.1"))
    data3C.2 <- subset(data2C, base.2 %in% c("T"), select=c("chrom", "position", "ref_base", "depth","base.2", "reads.2"))
    data3C.3 <- subset(data2C, base.3 %in% c("T"), select=c("chrom", "position", "ref_base", "depth","base.3", "reads.3"))
    data3C.4 <- subset(data2C, base.4 %in% c("T"), select=c("chrom", "position",  "ref_base", "depth","base.4", "reads.4"))

    #Change column names
    names(data3C.1)[names(data3C.1) == "base.1"] <- "base"
    names(data3C.1)[names(data3C.1) == "reads.1"] <- "reads"

    names(data3C.2)[names(data3C.2) == "base.2"] <- "base"
    names(data3C.2)[names(data3C.2) == "reads.2"] <- "reads"

    names(data3C.3)[names(data3C.3) == "base.3"] <- "base"
    names(data3C.3)[names(data3C.3) == "reads.3"] <- "reads"

    names(data3C.4)[names(data3C.4) == "base.4"] <- "base"
    names(data3C.4)[names(data3C.4) == "reads.4"] <- "reads"

    # For data2G select the reads that have a A
    data3G.1 <- subset(data2G, base.1 %in% c("A"), select=c("chrom", "position", "ref_base", "depth", "base.1", "reads.1"))
    data3G.2 <- subset(data2G, base.2 %in% c("A"), select=c("chrom", "position", "ref_base", "depth", "base.2", "reads.2"))
    data3G.3 <- subset(data2G, base.3 %in% c("A"), select=c("chrom", "position", "ref_base", "depth", "base.3", "reads.3"))
    data3G.4 <- subset(data2G, base.4 %in% c("A"), select=c("chrom", "position", "ref_base", "depth","base.4", "reads.4"))

    #Change column names
    names(data3G.1)[names(data3G.1) == "base.1"] <- "base"
    names(data3G.1)[names(data3G.1) == "reads.1"] <- "reads"

    names(data3G.2)[names(data3G.2) == "base.2"] <- "base"
    names(data3G.2)[names(data3G.2) == "reads.2"] <- "reads"

    names(data3G.3)[names(data3G.3) == "base.3"] <- "base"
    names(data3G.3)[names(data3G.3) == "reads.3"] <- "reads"

    names(data3G.4)[names(data3G.4) == "base.4"] <- "base"
    names(data3G.4)[names(data3G.4) == "reads.4"] <- "reads"

    # Combine these datasets into one, sort and determine the mutation frequency
    All_Off <- rbind(data3C.1,data3C.2,data3C.3,data3C.4,data3G.1,data3G.2,data3G.3,data3G.4, fill=TRUE)
    All_Off$position <- as.numeric(All_Off$position)
    All_Off <- All_Off[order(All_Off$position),]
    All_Off$depth <- as.numeric(All_Off$depth)
    All_Off$reads <- as.numeric(All_Off$reads)

    data3 <- All_Off <- transform(All_Off , percentage = (reads / depth)*100)
    DuplicateList <- All_Off$position

   # Add positions without off-targets
    dataCG <- dataCG[, c(
      "chrom",
      "position",
      "ref_base",
      "depth"
    ), drop = FALSE]
    dataCG[, 'base'] = NA
    dataCG[, 'reads'] = NA
    dataCG[, 'percentage'] = NA
    test <- rbind(data3, dataCG)
    test2 <- test[ ! test$position %in% DuplicateList, ]
    test2$percentage[is.na(test2$percentage)] <- 0

    AllCG <- rbind(data3, test2)

    the_dir <- file.path(out_dir_base, "percentages") #Name the new desired directory
     check_create_dir(the_dir)

     # write as new csv
     write_csv(AllCG,file = paste0(the_dir,"/", file_path_sans_ext(basename(input)), ".csv", sep=""))
     the_dir <- file.path(out_dir_base, "mean") #Name the new desired directory
     check_create_dir(the_dir)

     # Calulate mean percentage without on target
     data_off <- AllCG[!(AllCG$position %in% OntargetPosition),]
     mean <- mean(data_off$percentage)

     # Save mean as separate file
     write.table(mean, file = paste0(the_dir, "/", file_path_sans_ext(basename(input)), '_mean',".txt"))

     # Extract on target percentage
     ontarget <- data3[(data3$position == OntargetPosition),]

     the_dir <- file.path(out_dir_base, "OnTarget") #Name the new desired directory
     check_create_dir(the_dir)

     # As the mutations can be in any column, do this for ontarget:
     if (isTRUE(ontarget$base.1 == "A") ==TRUE) {
       ontarget <- transform(ontarget , percentage = (reads.1 / depth)*100) # isTRUE(condition)==TRUE to avoid error if NA
     } else if (isTRUE(ontarget$base.2 == "A") ==TRUE) {
       ontarget <- transform(ontarget , percentage = (reads.2 / depth)*100)
     } else if (isTRUE(ontarget$base.3 == "A") ==TRUE){
       ontarget <- transform(ontarget , percentage = (reads.3 / depth)*100)
     } else if (isTRUE(ontarget$base.4 == "A") ==TRUE) {
       ontarget <- transform(ontarget , percentage = (reads.4 / depth)*100)
     } else if (isTRUE(ontarget$base.1 == "T") ==TRUE) {
       ontarget <- transform(ontarget , percentage = (reads.2 / depth)*100)
     } else if (isTRUE(ontarget$base.2 == "T") ==TRUE) {
       ontarget <- transform(ontarget , percentage = (reads.2 / depth)*100)
     } else if (isTRUE(ontarget$base.3 == "T") ==TRUE){
       ontarget <- transform(ontarget , percentage = (reads.3 / depth)*100)
     } else if (isTRUE(ontarget$base.4 == "T") ==TRUE) {
       ontarget <- transform(ontarget , percentage = (reads.4 / depth)*100)
     }   else{
         print ("NA")
       }

     # Save ontarget as separate file
     write.table(ontarget$percentage,file = paste0(the_dir, "/", file_path_sans_ext(basename(input)), '_ontarget',".txt"))

     ################# Add average coverage ################

     the_dir <- file.path(out_dir_base, "Coverage") #Name the new desired directory
     check_create_dir(the_dir)

     # Calculate average coverage and save as separate file
     coverage <- mean(data$depth)
     write.table(coverage,file = paste0(the_dir, "/", file_path_sans_ext(basename(input)), '_coverage',".txt"))

     ### Create files with all positions, but only off targets and no background
     idx <- match(data$position, AllCG$position)
     data$MutBase <- AllCG$base[idx]
     data$MutReads <- AllCG$reads[idx]
     data$percentage <-AllCG$percentage[idx]
     data <- data[, c(
       "chrom",
       "position",
       "ref_base",
       "depth",
       "base.1",
       "reads.1",
       "MutBase",
       "MutReads",
       "percentage"
     ), drop = FALSE]

     names(data)[names(data) == "base.1"] <- "RefBase"
     names(data)[names(data) == "reads.1"] <- "RefReads"

     # Save all positions file
     the_dir <- file.path(out_dir_base, "AllPositions")
     check_create_dir(the_dir)

     write_csv(data,file = paste0(the_dir,"/", file_path_sans_ext(basename(input)), ".csv", sep=""))

  }
  lapply(MinXFiles, process_file)
  invisible(NULL)
}
