#' OnTargetCalcABE
#'
#' This function allows you to perform all necessary calculations for adenine base editing on and off target effects
#' @param MinXFiles A character vector of file paths
#' @param OntargetPosition Numeric. Genomic position of the intended on-target
#'   editing site.
#' @param out_dir_base Base output directory. Defaults to the current working
#'   directory (`"."`). The `percentages`, `mean`, `OnTarget`, `Coverage`,
#'   and `AllPositions` subdirectories are created within this directory.
#' @keywords Load counts and filter for minimum depth (default = 30)
#' @export
#' @examples
#' \dontrun{
#' # Usage example
#' file_paths <- c("file1.csv", "file2.csv", "file3.csv")
#' OnTargetCalcABE(file_paths, OntargetPosition = 1561)
#' }

OnTargetCalcABE <- function(
    MinXFiles,
    OntargetPosition,
    out_dir_base = "."
) {
  if (any(!file.exists(MinXFiles))) {
    stop("One or more input files not found.")
  }

  process_file <- function(input) {
    message("Processing: ", input)
    data <- read.delim(input, row.names = NULL, header = T, sep = ",")

    # Install the 'splitstackshape' package if needed: install.packages("splitstackshape")
    if (!requireNamespace("splitstackshape", quietly = TRUE)) {
      stop("Please install the 'splitstackshape' package to use the 'concat.split' function.")
    }

    # Identify the VarScan allele columns generated by LoadRawCount()
    allele_cols <- intersect(
      c("A6", "A7", "A8", "A9"),
      names(data)
    )

    if (length(allele_cols) == 0) {
      stop(
        "No VarScan allele columns (A6-A9) were found in the input file: ",
        basename(input)
      )
    }

    # Split the VarScan allele fields into their named components.
    # Component 1 contains the allele/base and component 2 the read count.
    data <- splitstackshape::concat.split(
      data = data,
      split.col = allele_cols,
      sep = ":",
      drop = TRUE
    )

    allele_pair_cols <- unlist(
      lapply(
        allele_cols,
        function(x) paste0(x, c("_1", "_2"))
      ),
      use.names = FALSE
    )

    required_cols <- c(
      "chrom",
      "position",
      "ref_base",
      "depth",
      allele_pair_cols
    )

    missing_cols <- setdiff(required_cols, names(data))

    if (length(missing_cols) > 0) {
      stop(
        "Required columns are missing after parsing VarScan data: ",
        paste(missing_cols, collapse = ", ")
      )
    }

    # Select columns by name rather than by numeric position
    data <- data[, required_cols, drop = FALSE]

    # Add columns if they don't exist
    rename_map <- c(
      A6_1 = "base.1",
      A6_2 = "reads.1",
      A7_1 = "base.2",
      A7_2 = "reads.2",
      A8_1 = "base.3",
      A8_2 = "reads.3",
      A9_1 = "base.4",
      A9_2 = "reads.4"
    )

    for (old_name in names(rename_map)) {
      if (old_name %in% names(data)) {
        names(data)[names(data) == old_name] <- rename_map[[old_name]]
      }
    }

    # Ensure all four nucleotide allele slots exist.
    # VarScan output can contain fewer allele fields when some bases are absent.
    for (i in 1:4) {
      base_col <- paste0("base.", i)
      reads_col <- paste0("reads.", i)

      if (!base_col %in% names(data)) {
        data[[base_col]] <- NA_character_
      }

      if (!reads_col %in% names(data)) {
        data[[reads_col]] <- NA_real_
      }
    }

    # Select all A
    data2A <- data[data$ref_base %in% c("A"),]
    # Select all T
    data2T <- data[data$ref_base %in% c("T"),]
    # Combine data2A and data2T for later
    dataAT <- rbind(data2A, data2T)

    # For data2A select the reads that have a G
    data3A.1 <- subset(data2A, base.1 %in% c("G"), select=c("chrom", "position",  "ref_base", "depth", "base.1", "reads.1"))
    data3A.2 <- subset(data2A, base.2 %in% c("G"), select=c("chrom", "position", "ref_base", "depth","base.2", "reads.2"))
    data3A.3 <- subset(data2A, base.3 %in% c("G"), select=c("chrom", "position", "ref_base", "depth","base.3", "reads.3"))
    data3A.4 <- subset(data2A, base.4 %in% c("G"), select=c("chrom", "position",  "ref_base", "depth","base.4", "reads.4"))

    #Change column names
    names(data3A.1)[names(data3A.1) == "base.1"] <- "base"
    names(data3A.1)[names(data3A.1) == "reads.1"] <- "reads"

    names(data3A.2)[names(data3A.2) == "base.2"] <- "base"
    names(data3A.2)[names(data3A.2) == "reads.2"] <- "reads"

    names(data3A.3)[names(data3A.3) == "base.3"] <- "base"
    names(data3A.3)[names(data3A.3) == "reads.3"] <- "reads"

    names(data3A.4)[names(data3A.4) == "base.4"] <- "base"
    names(data3A.4)[names(data3A.4) == "reads.4"] <- "reads"

    # For data2T select the reads that have a C
    data3T.1 <- subset(data2T, base.1 %in% c("C"), select=c("chrom", "position", "ref_base", "depth", "base.1", "reads.1"))
    data3T.2 <- subset(data2T, base.2 %in% c("C"), select=c("chrom", "position", "ref_base", "depth", "base.2", "reads.2"))
    data3T.3 <- subset(data2T, base.3 %in% c("C"), select=c("chrom", "position", "ref_base", "depth", "base.3", "reads.3"))
    data3T.4 <- subset(data2T, base.4 %in% c("C"), select=c("chrom", "position", "ref_base", "depth","base.4", "reads.4"))

    #Change column names
    names(data3T.1)[names(data3T.1) == "base.1"] <- "base"
    names(data3T.1)[names(data3T.1) == "reads.1"] <- "reads"

    names(data3T.2)[names(data3T.2) == "base.2"] <- "base"
    names(data3T.2)[names(data3T.2) == "reads.2"] <- "reads"

    names(data3T.3)[names(data3T.3) == "base.3"] <- "base"
    names(data3T.3)[names(data3T.3) == "reads.3"] <- "reads"

    names(data3T.4)[names(data3T.4) == "base.4"] <- "base"
    names(data3T.4)[names(data3T.4) == "reads.4"] <- "reads"

    # Combine these datasets into one, sort and determine the mutation frequency
    All_Off <- rbind(data3A.1,data3A.2,data3A.3,data3A.4,data3T.1,data3T.2,data3T.3,data3T.4, fill=TRUE)
    All_Off$position <- as.numeric(All_Off$position)
    All_Off <- All_Off[order(All_Off$position),]
    All_Off$depth <- as.numeric(All_Off$depth)
    All_Off$reads <- as.numeric(All_Off$reads)

    data3 <- All_Off <- transform(All_Off , percentage = (reads / depth)*100)
    DuplicateList <- All_Off$position

   # Add positions without off-targets
    dataAT <- dataAT[, c(
      "chrom",
      "position",
      "ref_base",
      "depth"
    ), drop = FALSE]
    dataAT[, 'base'] = NA
    dataAT[, 'reads'] = NA
    dataAT[, 'percentage'] = NA
    test <- rbind(data3, dataAT)
    test2 <- test[ ! test$position %in% DuplicateList, ]
    test2$percentage[is.na(test2$percentage)] <- 0

    AllAT <- rbind(data3, test2)

    the_dir <- file.path(out_dir_base, "percentages") #Name the new desired directory
     check_create_dir(the_dir)

     # write as new csv
     write_csv(AllAT,file = paste0(the_dir,"/", file_path_sans_ext(basename(input)), ".csv", sep=""))
     the_dir <- file.path(out_dir_base, "mean") #Name the new desired directory
     check_create_dir(the_dir)

     # Calulate mean percentage without on target
     data_off <- AllAT[!(AllAT$position %in% OntargetPosition),]
     mean <- mean(data_off$percentage)

     # Save mean as separate file
     write.table(mean, file = paste0(the_dir, "/", file_path_sans_ext(basename(input)), '_mean',".txt"))

     # Extract on target percentage
     ontarget <- data3[(data3$position == OntargetPosition),]

     the_dir <- file.path(out_dir_base, "OnTarget") #Name the new desired directory
     check_create_dir(the_dir)

     # As the mutations can be in any column, do this for ontarget:
     if (isTRUE(ontarget$base.1 == "G") ==TRUE) {
       ontarget <- transform(ontarget , percentage = (reads.1 / depth)*100) # isTRUE(condition)==TRUE to avoid error if NA
     } else if (isTRUE(ontarget$base.2 == "G") ==TRUE) {
       ontarget <- transform(ontarget , percentage = (reads.2 / depth)*100)
     } else if (isTRUE(ontarget$base.3 == "G") ==TRUE){
       ontarget <- transform(ontarget , percentage = (reads.3 / depth)*100)
     } else if (isTRUE(ontarget$base.4 == "G") ==TRUE) {
       ontarget <- transform(ontarget , percentage = (reads.4 / depth)*100)
     } else if (isTRUE(ontarget$base.1 == "C") ==TRUE) {
       ontarget <- transform(ontarget , percentage = (reads.2 / depth)*100)
     } else if (isTRUE(ontarget$base.2 == "C") ==TRUE) {
       ontarget <- transform(ontarget , percentage = (reads.2 / depth)*100)
     } else if (isTRUE(ontarget$base.3 == "C") ==TRUE){
       ontarget <- transform(ontarget , percentage = (reads.3 / depth)*100)
     } else if (isTRUE(ontarget$base.4 == "C") ==TRUE) {
       ontarget <- transform(ontarget , percentage = (reads.4 / depth)*100)
     }  else{
       print ("NA")
     }

     # Save ontarget as separate file
     write.table(ontarget$percentage,file = paste0(the_dir, "/", file_path_sans_ext(basename(input)), '_ontarget',".txt"))

     ################# Add average coverage ################

     the_dir <- file.path(out_dir_base, "Coverage") #Name the new desired directory
     check_create_dir(the_dir)

     # Calculate average coverage and save as separate file
     coverage <- mean(data$depth)
     write.table(coverage,file = paste0(the_dir, "/", file_path_sans_ext(basename(input)), '_coverage',".txt"))

     ### Create files with all positions, but only off targets and no background
     idx <- match(data$position, AllAT$position)
     data$MutBase <- AllAT$base[idx]
     data$MutReads <- AllAT$reads[idx]
     data$percentage <-AllAT$percentage[idx]
     data <- data[, c(
       "chrom",
       "position",
       "ref_base",
       "depth",
       "base.1",
       "reads.1",
       "MutBase",
       "MutReads",
       "percentage"
     ), drop = FALSE]

     names(data)[names(data) == "base.1"] <- "RefBase"
     names(data)[names(data) == "reads.1"] <- "RefReads"

     # Save all positions file
     the_dir <- file.path(out_dir_base, "AllPositions")
     check_create_dir(the_dir)

     write_csv(data,file = paste0(the_dir,"/", file_path_sans_ext(basename(input)), ".csv", sep=""))

  }
  lapply(MinXFiles, process_file)
  invisible(NULL)
}
