  #' OnVsOffTargetAdj
  #'
  #' Plot on-target versus adjusted off-target editing
  #'
  #' Creates a scatter plot comparing on-target editing with mean
  #' background-adjusted off-target editing for each sample. Mean adjusted
  #' off-target editing values are obtained from the output of
  #' \code{\link{AdjustedMeanCalc}}.
  #'
  #' @param AdjustedMean Data frame containing mean background-adjusted
  #'   off-target editing values generated by \code{\link{AdjustedMeanCalc}}.
  #'   Must contain \code{FileName} and \code{Off target \%}.
  #' @param All_ontarget Data frame containing on-target editing results.
  #'   Must contain \code{FileName} and \code{On target \%}.
  #' @param SampleList Data frame containing sample metadata. Must contain
  #'   \code{FileName}, \code{SampleName}, and \code{Condition}.
  #' @param xlab Character. Label for the x-axis.
  #' @param ylab Character. Label for the y-axis.
  #' @param ggtitle Character. Plot title.
  #' @param condition Logical. If TRUE, points are grouped and coloured by
  #'   condition.
  #' @param out_dir_base Base analysis directory. Defaults to the current working
  #'   directory (\code{"."}). Output files are written to the
  #'   \code{Plots/AdjustedPlots} subdirectory.
  #'
  #' @return Invisibly returns the ggplot object. PNG and PDF versions of the
  #'   plot are saved to the \code{Plots/AdjustedPlots} subdirectory within
  #'   \code{out_dir_base}.
  #'
  #' @export
  #'
  #' @examples
  #' \dontrun{
  #' AdjustedMean <- AdjustedMeanCalc(
  #'   Adj = Adj,
  #'   OntargetPosition = 1561
  #' )
  #'
  #' OnVsOffTargetAdj(
  #'   AdjustedMean = AdjustedMean,
  #'   All_ontarget = OnTarget,
  #'   SampleList = SampleList
  #' )
  #' }

OnVsOffTargetAdj <- function(
    AdjustedMean,
    All_ontarget,
    SampleList,
    xlab = "Adjusted off-target editing (%)",
    ylab = "On-target editing (%)",
    ggtitle = "On-target versus off-target effects",
    condition = TRUE,
    out_dir_base = "."
) {

  # Check required columns
  required_mean_columns <- c(
    "FileName",
    "SampleName",
    "Condition",
    "Off target %"
  )

  missing_mean_columns <- setdiff(
    required_mean_columns,
    names(AdjustedMean)
  )

  if (length(missing_mean_columns) > 0) {
    stop(
      "Error: Missing required column(s) in AdjustedMean: ",
      paste(missing_mean_columns, collapse = ", ")
    )
  }

  if (!"FileName" %in% names(All_ontarget)) {
    stop("Error: 'All_ontarget' must contain a 'FileName' column.")
  }

  if (!"On target %" %in% names(All_ontarget)) {
    stop("Error: 'All_ontarget' must contain an 'On target %' column.")
  }

  # Retain the sample-level adjusted mean calculated by AdjustedMeanCalc()
  data <- AdjustedMean %>%
    dplyr::filter(!is.na(.data$`Off target %`))

  # Join on-target values by FileName
  Overview_adj <- dplyr::left_join(
    data,
    All_ontarget,
    by = "FileName"
  )

  Overview_adj$`On target %` <- as.numeric(
    Overview_adj$`On target %`
  )

  # Check that on-target values were matched
  if (any(is.na(Overview_adj$`On target %`))) {
    warning(
      "One or more samples in AdjustedMean could not be matched ",
      "to an on-target value in All_ontarget."
    )
  }

  # Determine label/colour grouping
  if (condition) {

    num_groups <- length(
      unique(Overview_adj$Condition)
    )

    if (
      num_groups >
      RColorBrewer::brewer.pal.info["Dark2", "maxcolors"]
    ) {
      stop(
        "Too many conditions to display with the 'Dark2' palette. ",
        "Reduce groups or use a different palette."
      )
    }

    color_palette <- RColorBrewer::brewer.pal(
      num_groups,
      "Dark2"
    )

  } else {

    color_palette <- NULL
  }

  # Dynamic label size based on longest sample name
  max_label_length <- max(
    nchar(Overview_adj$SampleName),
    na.rm = TRUE
  )

  label_size <- dplyr::case_when(
    max_label_length <= 10 ~ 3.5,
    max_label_length <= 15 ~ 3.2,
    max_label_length <= 20 ~ 3.0,
    TRUE                   ~ 2.8
  )

  # Create plot
  if (condition) {

    p <- ggplot2::ggplot(
      Overview_adj,
      ggplot2::aes(
        x = .data$`Off target %`,
        y = .data$`On target %`,
        colour = .data$Condition
      )
    )

  } else {

    p <- ggplot2::ggplot(
      Overview_adj,
      ggplot2::aes(
        x = .data$`Off target %`,
        y = .data$`On target %`
      )
    )
  }

  p <- p +
    ggplot2::geom_point(size = 3) +
    ggrepel::geom_text_repel(
      ggplot2::aes(label = .data$SampleName),
      size = label_size,
      box.padding = grid::unit(0.3, "lines")
    ) +
    ggplot2::expand_limits(
      x = 0,
      y = 0
    ) +
    ggplot2::labs(
      title = ggtitle,
      x = xlab,
      y = ylab,
      colour = if (condition) "Condition" else NULL
    ) +
    ggplot2::theme_classic(base_size = 11) +
    ggplot2::theme(
      axis.text = ggplot2::element_text(size = 10),
      axis.title = ggplot2::element_text(size = 12),
      plot.title = ggplot2::element_text(size = 13),
      legend.text = ggplot2::element_text(size = 12),
      legend.title = ggplot2::element_text(size = 12),
      legend.position = if (condition) "right" else "none"
    )

  if (condition) {
    p <- p +
      ggplot2::scale_color_manual(
        values = color_palette
      )
  }

  # Save plots
  the_dir <- file.path(
    out_dir_base,
    "Plots",
    "AdjustedPlots"
  )

  check_create_dir(the_dir)

  ggplot2::ggsave(
    file.path(
      the_dir,
      "OnOffTarget_Adj.png"
    ),
    plot = p,
    width = 7,
    height = 5,
    dpi = 300
  )

  ggplot2::ggsave(
    file.path(
      the_dir,
      "OnOffTarget_Adj.pdf"
    ),
    plot = p,
    width = 7,
    height = 5
  )

  invisible(p)
}
