#' Plot Grouped Off-Target Editing
#'
#' Create a grouped bar chart of mean adjusted off-target editing
#'
#' Uses the sample-level mean background-adjusted off-target editing values
#' generated by \code{\link{AdjustedMeanCalc}} and groups samples using the
#' \code{CombinedName} column in \code{SampleList}.
#'
#' Bars show the group mean, individual sample values can be overlaid as
#' points, and error bars show the standard deviation (SD) or standard error
#' of the mean (SEM).
#'
#' This function summarises the overall adjusted off-target editing level and
#' does not apply the empirical background threshold used to identify
#' individual off-target positions.
#'
#' @param AdjustedMean Data frame containing sample-level mean
#'   background-adjusted off-target editing values generated by
#'   \code{\link{AdjustedMeanCalc}}. Must contain \code{FileName} and
#'   \code{Off target \%}.
#' @param SampleList Data frame containing sample metadata. Must contain
#'   \code{FileName} and \code{CombinedName}.
#' @param error Character. Error bar to display. Either \code{"SD"} (default),
#'   \code{"SEM"}, or \code{"none"}.
#' @param show_points Logical. If TRUE (default), individual sample-level mean
#'   off-target editing percentages are shown as points.
#' @param y_max Optional numeric value specifying the maximum displayed
#'   y-axis value. If NULL (default), the y-axis is scaled automatically.
#' @param out_dir_base Base output directory. Defaults to the current working
#'   directory (\code{"."}).
#'
#' @return Invisibly returns a list containing the plot (\code{plot}), the
#'   sample-level mean off-target editing data (\code{data}), and the group
#'   summary (\code{summary}). The plot is also saved as PNG and PDF and the
#'   summary and sample-level data are saved as CSV files.
#'
#' @export
PlotGroupedOffTarget <- function(
    AdjustedMean,
    SampleList,
    error = "SD",
    show_points = TRUE,
    y_max = NULL,
    out_dir_base = "."
) {

  # Check arguments --------------------------------------------------------

  error <- toupper(error)

  if (!error %in% c("SD", "SEM", "NONE")) {
    stop(
      "error must be one of: 'SD', 'SEM', or 'none'."
    )
  }

  required_mean <- c(
    "FileName",
    "Off target %"
  )

  missing_mean <- setdiff(
    required_mean,
    names(AdjustedMean)
  )

  if (length(missing_mean) > 0) {
    stop(
      "AdjustedMean is missing required column(s): ",
      paste(missing_mean, collapse = ", ")
    )
  }

  required_samplelist <- c(
    "FileName",
    "CombinedName"
  )

  missing_samplelist <- setdiff(
    required_samplelist,
    names(SampleList)
  )

  if (length(missing_samplelist) > 0) {
    stop(
      "SampleList is missing required column(s): ",
      paste(missing_samplelist, collapse = ", ")
    )
  }


  # Prepare sample-level data ---------------------------------------------

  sample_summary <- AdjustedMean

  sample_summary$`Off target %` <-
    suppressWarnings(
      as.numeric(sample_summary$`Off target %`)
    )

  # Standardise filenames
  sample_summary$FileName <- sub(
    "_counts$",
    "",
    sample_summary$FileName
  )

  sample_summary$FileName <- sub(
    "_R30$",
    "",
    sample_summary$FileName
  )

  # Use a simpler internal column name for plotting and summaries
  sample_summary$MeanOffTarget <-
    sample_summary$`Off target %`


  # Add group information -------------------------------------------------

  idx <- match(
    sample_summary$FileName,
    SampleList$FileName
  )

  sample_summary$CombinedName <-
    SampleList$CombinedName[idx]

  if (anyNA(sample_summary$CombinedName)) {

    unmatched <- unique(
      sample_summary$FileName[
        is.na(sample_summary$CombinedName)
      ]
    )

    stop(
      "Sample metadata could not be matched for: ",
      paste(unmatched, collapse = ", ")
    )
  }


  # Preserve SampleList group order ---------------------------------------

  group_order <- unique(
    SampleList$CombinedName[
      SampleList$CombinedName %in%
        sample_summary$CombinedName
    ]
  )

  sample_summary$CombinedName <- factor(
    sample_summary$CombinedName,
    levels = group_order
  )


  # Calculate group statistics -------------------------------------------

  group_summary <- sample_summary |>
    dplyr::group_by(.data$CombinedName) |>
    dplyr::summarise(
      n = sum(!is.na(.data$MeanOffTarget)),
      Mean = mean(
        .data$MeanOffTarget,
        na.rm = TRUE
      ),
      SD = stats::sd(
        .data$MeanOffTarget,
        na.rm = TRUE
      ),
      SEM = .data$SD / sqrt(.data$n),
      .groups = "drop"
    )

  # SD and SEM are undefined for n = 1
  group_summary$SD[
    group_summary$n < 2
  ] <- NA_real_

  group_summary$SEM[
    group_summary$n < 2
  ] <- NA_real_


  # Select error bar ------------------------------------------------------

  if (error == "SD") {
    group_summary$Error <- group_summary$SD
  }

  if (error == "SEM") {
    group_summary$Error <- group_summary$SEM
  }

  if (error == "NONE") {
    group_summary$Error <- 0
  }


  # Create plot -----------------------------------------------------------

  p <- ggplot2::ggplot(
    group_summary,
    ggplot2::aes(
      x = .data$CombinedName,
      y = .data$Mean
    )
  ) +
    ggplot2::geom_col(
      width = 0.7
    )

  if (error != "NONE") {

    p <- p +
      ggplot2::geom_errorbar(
        ggplot2::aes(
          ymin = pmax(0, .data$Mean - .data$Error),
          ymax = .data$Mean + .data$Error
        ),
        width = 0.2
      )
  }

  if (show_points) {

    p <- p +
      ggplot2::geom_point(
        data = sample_summary,
        ggplot2::aes(
          x = .data$CombinedName,
          y = .data$MeanOffTarget
        ),
        inherit.aes = FALSE,
        position = ggplot2::position_jitter(
          width = 0.08,
          height = 0
        ),
        size = 2.5
      )
  }

  p <- p +
    ggplot2::labs(
      x = NULL,
      y = "Mean adjusted off-target editing (%)"
    ) +
    ggplot2::scale_y_continuous(
      expand = ggplot2::expansion(
        mult = c(0, 0.08)
      )
    ) +
    ggplot2::theme_classic() +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(
        angle = 45,
        hjust = 1
      )
    )

  # Optionally restrict displayed y-axis range without removing data
  if (!is.null(y_max)) {
    p <- p +
      ggplot2::coord_cartesian(
        ylim = c(0, y_max)
      )
  }


  # Save results ----------------------------------------------------------

  output_dir <- file.path(
    out_dir_base,
    "GroupedBarChart"
  )

  check_create_dir(output_dir)

  readr::write_csv(
    sample_summary,
    file.path(
      output_dir,
      "Grouped_OffTarget_sample_means.csv"
    )
  )

  readr::write_csv(
    group_summary,
    file.path(
      output_dir,
      "Grouped_OffTarget_summary.csv"
    )
  )

  ggplot2::ggsave(
    filename = file.path(
      output_dir,
      "Grouped_OffTarget_barplot.png"
    ),
    plot = p,
    width = 9,
    height = 6,
    dpi = 300
  )

  ggplot2::ggsave(
    filename = file.path(
      output_dir,
      "Grouped_OffTarget_barplot.pdf"
    ),
    plot = p,
    width = 9,
    height = 6
  )


  # Return results --------------------------------------------------------

  invisible(
    list(
      plot = p,
      data = sample_summary,
      summary = group_summary
    )
  )
}
